name: build
on: push
jobs:
  typescript-from-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup PROTOC compiler
        uses: abelfodil/protoc-action@v1
          with:
            protoc-version: '3.13.0'
