name: build
on: push
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: docker run -v `pwd`:/defs namely/protoc-all -d . -l java
