name: build
on: push
jobs:
  java-from-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
#
#      - name: Set up JDK 13
#        uses: actions/setup-java@v1
#        with:
#          java-version: 13
#
#      - name: Building Protos
#        run: ./gradlew build
#
#      - name: Bintray Upload
#        env:
#          JFROG_USER: ${{ secrets.JFROG_USER }}
#          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
#        run: |
#          ./gradlew bintrayUpload
  typescript-from-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup PROTOC compiler
        uses: abelfodil/protoc-action@v1
        with:
          protoc-version: '3.13.0'

